### ISSUE TITLE
Unseal `TextCodec` to allow custom query parameter enc/decoding

### ISSUE THREAD

**Issue by anqit** [zio/zio-http#2945]
**Is your feature request related to a problem? Please describe.**
I would like to decode query parameters to custom objects. Currently, we can use functions like `URL#queryParamTo[T]` to decode query params to any type that has a `TextCodec` available, however, unlike other codec related classes (`BinaryCodec`, `Schema`, etc), `TextCodec` is sealed. This means we can only decode query params to a small, pre-determined set of types.

**Describe the solution you'd like**
Maybe there's some limitation I'm unaware of, but I don't see why `TextCodec` has to be sealed. It would be useful if it weren't, so that we could make custom ones to decode query parameters to any custom type. Additionally, it would then be helpful to have methods like `transform` and ilk to be able to generate new `TextCodec` instances from existing ones.

**Describe alternatives you've considered**
Currently, I have to do something like 

```scala
(req: Request) =>
                req.url.queryParamTo[String]("myParam").map(stringToMyCustomTypeConverter)...
```
whereas, with the ability to create custom `TextCodec`s, we could just do:

```scala
(req: Request) =>
                req.url.queryParamTo[MyCustomType]("myParam")...
```

**Comment by 987Nabil** [comment]
Unsealing `TextCodec` is not possible. It would break garanties that we rely on in other places.
If you want to use easy custom mapping of query params, please use the Endpoint API.

There was an idea before though, to extract query params to case classes (not by opening `TextCodec`)
@jdegoes do you know what happened to it, I remember someone tried to implement some schema based solution.

**Comment by anqit** [comment]
I see, I've been meaning to check out the Endpoint API anyways, maybe this will be a good impetus to do that.
That said, seems like having variants of the query param extraction functions that use `Schema` instead of `TextCodec` could work

**Comment by jdegoes** [comment]
I don't think the correct solution is to unseal `TextCodec`, but rather, to allow use of any type that has a ZIO Schema.

If the query parameter does not have the structure necessary to encode / decode from a text-based query string parameter, then that would become a runtime failure.

/bounty $250 for a solution and tests

**Comment by guersam** [comment]
@987Nabil I'm not sure it's fully resolved by #2937, because the extracter in `QueryGetters` still require `TextCodec` rather than `QueryCodec`. Is there any way to make them work with `QueryCodec` keeping binary compatible?

**Comment by anqit** [comment]
I'm still unable to get this to work without using `transform` on a `QueryCodec`. If try to create a codec with `QueryCodec.query[A]` with a given `Schema[A]` in scope without using transform, I get a runtime error: `Only primitive types, sequences, sets, optional, enums and records with a single field can be used to infer query codecs`.

Is there another way to do this?

**Comment by 987Nabil** [comment]
@anqit i think there was a bug, that lazy schemas have not been handled correctly. I think I fixed that on main. Can you try a snapshot build?

**Comment by 987Nabil** [comment]
Except you have an object, then it is `queryAll[MyObject]`
